const assert = require('node:assert/strict');
const fs = require('node:fs');
const {filter,participant} = require('../agenda-filters.js');
const rows = JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../rooms.json')));
const all = {day:'',streams:[],type:'',product:'',query:'',includeShared:true};
assert.equal(filter(rows,all).length,95);
assert.equal(filter(rows,{...all,day:'Day 1'}).length,47);
assert.equal(filter(rows,{...all,day:'Day 2'}).length,48);
const combined = filter(rows,{...all,day:'Day 2',streams:['PLM'],type:'Breakout',query:'FHIR 1E'});
assert.equal(combined.length,1);assert.match(combined[0].product,/FHIR/i);assert.equal(combined[0].location,'1E');
const multi=filter(rows,{...all,day:'Day 2',streams:['PLM','MON'],type:'Breakout'});
assert.ok(multi.some(r=>r.vs==='PLM'));assert.ok(multi.some(r=>r.vs==='MON'));assert.ok(multi.every(r=>['PLM','MON'].includes(r.vs)));
const product=participant(rows.find(r=>r.day==='Day 2' && r.type==='Breakout' && r.product==='ePI'));
const shared=filter(rows,{...all,day:'Day 2',product});
assert.ok(shared.some(r=>r.product==='ePI'));assert.ok(shared.some(r=>r.vs==='ALL'));assert.ok(shared.some(r=>r.type==='Plenary' && r.vs==='PLM'));assert.ok(!shared.some(r=>r.type==='Plenary' && r.vs==='MON'));
assert.equal(filter(rows,{...all,day:'Day 2',product,includeShared:false}).length,1);
assert.equal(filter(rows,{...all,query:'nothing-will-match-this'}).length,0);
assert.ok(filter(rows,{...all,streams:['PLM'],includeShared:false}).every(r=>r.vs==='PLM'));
assert.equal(filter(rows,{...all,day:'Day 2',type:'Plenary',query:'overall'}).length,1);
console.log('PASS: day, multiple streams, cross-field search, combined filters, product-specific plenaries, shared-session toggle, empty results.');
